openapi: 3.1.0
info:
  title: Google Drive GPT
  version: 1.0.0
  description: Access and analyze files from a specific Google Drive folder using your proxy.

servers:
  - url: https://google-drive-gpt-3.vercel.app

paths:
  /api/files/list:
    get:
      operationId: listFiles
      summary: List files in a specific Google Drive folder
      parameters:
        - name: folderId
          in: query
          required: true
          description: The folder ID to list files from
          schema:
            type: string
      responses:
        '200':
          description: A list of files
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        mimeType:
                          type: string

  /api/files/content:
    get:
      operationId: readFileContent
      summary: Read the plain text content of a Google Docs file
      parameters:
        - name: fileId
          in: query
          required: true
          description: The ID of the file to read
          schema:
            type: string
      responses:
        '200':
          description: The plain text content of the file
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/drive.readonly: View files in your Google Drive

security:
  - OAuth2:
      - https://www.googleapis.com/auth/drive.readonly



